### ISSUE TITLE
Tick icon update

### ISSUE THREAD

**Issue by olipowell** [Financial-Times/fticons#32]
Updated the tick icon for improved clarity at smaller sizes such as checkboxes etc.

**Comment by olipowell** [comment]
[check.svg.zip](https://github.com/Financial-Times/fticons/files/1063659/check.svg.zip)

**Comment by olipowell** [comment]
[tick.zip](https://github.com/Financial-Times/fticons/files/1063666/tick.zip)

**Comment by JakeChampion** [comment]
PR for this #33
