### ISSUE TITLE
Add a video icon to the current set.

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/fticons#46]
Hi there, please can we add the following icon to the ft-icons set as KAT needs a video icon to show content type in a list. This will be used alongside the Newspaper and Podcast icons.

Cheers, 

James 

[video.svg.zip](https://github.com/Financial-Times/fticons/files/1501891/video.svg.zip)

**Comment by notlee** [comment]
https://github.com/Financial-Times/fticons/pull/47
