### ISSUE TITLE
Update the outside-page icon

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/fticons#54]
This is to update the style of this icon to better align with the wider style (arrow style etc.) and to allow for greater parity with the app which is using a similar looking icon instead of the Origami alternative. 

[outside-page-v2.svg.zip](https://github.com/Financial-Times/fticons/files/1907143/outside-page-v2.svg.zip)

**Comment by notlee** [comment]
Updated 👍 https://github.com/Financial-Times/fticons/releases/tag/v1.14.2
